# Generated by Django 4.2.7 on 2026-04-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='equipos/'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='ubicaciones/'),
        ),
    ]
