# Generated by Django 4.2.7 on 2026-04-04 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activos', '0002_equipo_imagen_ubicacion_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='codigo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='codigo',
            field=models.CharField(max_length=20),
        ),
    ]
