# Generated by Django 6.0.3 on 2026-09-23 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activos', '0003_alter_equipo_codigo_alter_ubicacion_codigo'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroOperaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='centros_operaciones', to='users.cliente')),
            ],
            options={
                'verbose_name': 'Centro de Operaciones',
                'verbose_name_plural': 'Centros de Operaciones',
            },
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='centro_operaciones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubicaciones', to='Activos.centrooperaciones'),
        ),
        migrations.AddConstraint(
            model_name='centrooperaciones',
            constraint=models.UniqueConstraint(fields=('cliente', 'codigo'), name='uniq_codigo_por_cliente'),
        ),
    ]
