# Generated by Django 4.2.7 on 2026-09-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_perfilusuario_centro_operaciones'),
        ('Activos', '0004_centrooperaciones_ubicacion_centro_operaciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ubicacion',
            name='centro_operaciones',
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='co',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='CentroOperaciones',
        ),
    ]
