# Generated by Django 4.2.7 on 2026-09-30 15:52

from django.db import migrations, models
from django.db.models import Count


def resolver_duplicados(apps, schema_editor):
    database = schema_editor.connection.alias
    modelos = (
        (apps.get_model('Activos', 'Equipo'), 'EQUIPO', 'nombre'),
        (apps.get_model('Activos', 'Ubicacion'), 'UBICACION', 'nombre'),
    )

    for model, etiqueta, campo_nombre in modelos:
        manager = model.objects.using(database)
        max_length = model._meta.get_field('codigo').max_length
        grupos = list(
            manager.values('codigo')
            .annotate(total=Count('pk'))
            .filter(total__gt=1)
            .order_by('codigo')
        )
        renombrados = 0

        print(f'=== RESOLVIENDO DUPLICADOS DE {etiqueta} ===')
        for grupo in grupos:
            codigo = grupo['codigo'] or ''
            duplicados = list(
                manager.filter(codigo=codigo)
                .order_by('pk')
                .values_list('pk', campo_nombre)
            )
            print(f"Código duplicado: {codigo!r} ({len(duplicados)} registros)")

            for pk, nombre in duplicados[1:]:
                sufijo_numero = 2
                while True:
                    sufijo = f'-{sufijo_numero}'
                    if len(sufijo) > max_length:
                        raise RuntimeError(
                            f'No se pudo generar un código único de hasta {max_length} caracteres '
                            f'para {etiqueta.lower()} id={pk}.'
                        )
                    nuevo_codigo = f'{codigo[:max_length - len(sufijo)]}{sufijo}'
                    if not manager.filter(codigo=nuevo_codigo).exists():
                        break
                    sufijo_numero += 1

                manager.filter(pk=pk).update(codigo=nuevo_codigo)
                print(f'  id={pk} ({nombre}): {codigo!r} -> {nuevo_codigo!r}')
                renombrados += 1

        print(f'Total {etiqueta.lower()} renombrados: {renombrados}')


def revertir_resolucion(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('Activos', '0005_remove_ubicacion_centro_operaciones_ubicacion_co_and_more'),
    ]

    operations = [
        migrations.RunPython(resolver_duplicados, revertir_resolucion),
        migrations.AlterField(
            model_name='equipo',
            name='codigo',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='codigo',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
