# Generated by Django 4.2.7 on 2026-09-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activos', '0005_remove_ubicacion_centro_operaciones_ubicacion_co_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='codigo',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='codigo',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
