"""
Django settings for gestion_mantenimiento project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BASE_DIR))

import os

# Cargar variables de entorno desde .env
from dotenv import load_dotenv
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-default-key-change-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

# Forzar DEBUG=False en Railway (producción)
if os.environ.get('RAILWAY_ENVIRONMENT'):
    DEBUG = False

# ALLOWED_HOSTS - Soporta múltiples hosts separados por coma
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')

# Agregar dominios de Railway automáticamente
if os.environ.get('RAILWAY_ENVIRONMENT'):
    railway_hosts = [
        'web-production-990bf.up.railway.app',  # Tu dominio específico
        '*.up.railway.app',  # Todos los subdominios de Railway
        '*.railway.app',     # Por si acaso
        '*',  # Temporal: permitir cualquier host para debug
    ]
    for host in railway_hosts:
        if host not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(host)

# Debug: imprimir ALLOWED_HOSTS en Railway
if os.environ.get('RAILWAY_ENVIRONMENT'):
    print(f'ALLOWED_HOSTS: {ALLOWED_HOSTS}', file=sys.stderr)

# CSRF - Orígenes confiables para desarrollo local y producción
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'https://web-production-990bf.up.railway.app',
    'https://*.up.railway.app',
    'https://*.railway.app',
    'http://*',  # Temporal: permitir cualquier origen HTTP
    'https://*', # Temporal: permitir cualquier origen HTTPS
]

SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'False').lower() == 'true'

SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE = 'Lax'

SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Configuración de sesiones - Timeout después de 1 hora de inactividad
SESSION_COOKIE_AGE = 3600  # 1 hora en segundos
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Cerrar sesión al cerrar el navegador
SESSION_SAVE_EVERY_REQUEST = True  # Actualizar la fecha de expiración en cada solicitud


# Application definition

# Site ID para allauth
SITE_ID = 1

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',


    'gestion_mantenimiento.solicitudes',
    'gestion_mantenimiento.Activos',
    'gestion_mantenimiento.Gestion_ot',
    'crispy_forms',
    'mptt',
    'gestion_mantenimiento.users',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.microsoft',
    

]

CRISPY_TEMPLATE_PACK = 'bootstrap4'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'gestion_mantenimiento.middleware.LocalhostMiddleware',  # Redirigir 127.0.0.1 a localhost
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    # Debug middleware temporal
    'gestion_mantenimiento.middleware.DebugMiddleware',
]

if not DEBUG:
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

ROOT_URLCONF = 'gestion_mantenimiento.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'solicitudes.context_processors.is_admin',  # Añadir esta línea
            ],
        },
    },
]

WSGI_APPLICATION = 'gestion_mantenimiento.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

import dj_database_url

def get_absolute_sqlite_path(path_str):
    path = Path(path_str)
    if not path.is_absolute():
        path = BASE_DIR / path
    path.parent.mkdir(parents=True, exist_ok=True)
    path.touch(exist_ok=True)
    return path


def build_sqlite_url(path: Path) -> str:
    return f'sqlite:///{path}'


database_url = os.environ.get('DATABASE_URL')

if database_url:
    parsed_db = dj_database_url.parse(database_url)
    if parsed_db.get('ENGINE') == 'django.db.backends.sqlite3' and parsed_db.get('NAME'):
        parsed_db['NAME'] = str(get_absolute_sqlite_path(parsed_db['NAME']))
    DATABASES = {'default': parsed_db}
else:
    if os.environ.get('RAILWAY_STATIC_URL') or os.environ.get('RAILWAY_ENVIRONMENT') or os.environ.get('RAILWAY_SERVICE_ID'):
        default_path = Path('/data/db.sqlite3')
        try:
            default_path.parent.mkdir(parents=True, exist_ok=True)
            default_path.touch(exist_ok=True)
            database_url = build_sqlite_url(default_path)
        except OSError:
            fallback_path = get_absolute_sqlite_path(BASE_DIR / 'db.sqlite3')
            database_url = build_sqlite_url(fallback_path)
    else:
        fallback_path = get_absolute_sqlite_path(BASE_DIR / 'db.sqlite3')
        database_url = build_sqlite_url(fallback_path)
    DATABASES = {'default': dj_database_url.config(default=database_url)}

if DATABASES['default'].get('ENGINE') == 'django.db.backends.sqlite3':
    print('DATABASE PATH:', DATABASES['default'].get('NAME'), file=sys.stdout)


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Formatos de fecha y hora
DATE_FORMAT = 'd/m/Y'
DATETIME_FORMAT = 'd/m/Y H:i'
TIME_FORMAT = 'H:i'

# Formatos de entrada de fecha y hora
DATE_INPUT_FORMATS = ['%d/%m/%Y']
DATETIME_INPUT_FORMATS = ['%d/%m/%Y %H:%M']
TIME_INPUT_FORMATS = ['%H:%M']


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "gestion_mantenimiento" / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage' if not DEBUG else 'django.contrib.staticfiles.storage.StaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/topics/db/models/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

SITE_ID = 1

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

LOGIN_URL = '/accounts/login/'

# Configuración de Allauth
ACCOUNT_EMAIL_VERIFICATION = 'none'  # No requerir verificación de email
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = True

# Configuración de Site ID - importante para allauth
SITE_ID = 1

# Configuración de los proveedores sociales
# Nota: Los credenciales se cargan desde SocialApp en la BD,
# que es configurada automáticamente por el middleware
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

# settings.py

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Servidor SMTP de Gmail
EMAIL_PORT = 587  # Puerto SMTP para TLS
EMAIL_USE_TLS = True  # Usar TLS
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'your_email@gmail.com')  # Tu dirección de correo electrónico de Gmail
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'your_app_password')  # App password de Gmail
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER  # Dirección de correo electrónico predeterminada para enviar correos

EMAIL_ADICIONAL = 'juanesteban01010@gmail.com'  # Email adicional para copias

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}












