# Generated by Django 6.0.3 on 2026-09-23 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activos', '0004_centrooperaciones_ubicacion_centro_operaciones_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='centro_operaciones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles_usuario', to='Activos.centrooperaciones'),
        ),
    ]
