# Generated by Django 4.2.7 on 2026-09-23 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_perfilusuario_centro_operaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='centro_operaciones',
        ),
    ]
