# Generated by Django 4.2.7 on 2026-10-07 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_remove_perfilusuario_centro_operaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, help_text='Fecha del registro de asistencia.', verbose_name='Fecha')),
                ('hora_entrada', models.DateTimeField(blank=True, null=True, verbose_name='Hora de entrada')),
                ('hora_salida', models.DateTimeField(blank=True, null=True, verbose_name='Hora de salida')),
                ('horas_trabajadas', models.DecimalField(blank=True, decimal_places=2, help_text='Horas calculadas automáticamente cuando ambas marcas están disponibles.', max_digits=5, null=True, verbose_name='Horas trabajadas')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_asistencia', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de asistencia',
                'verbose_name_plural': 'Registros de asistencia',
                'ordering': ['-fecha', '-hora_entrada'],
                'unique_together': {('usuario', 'fecha')},
            },
        ),
    ]
