# Generated by Django 4.2.7 on 2026-10-07 23:30

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_add_registro_asistencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('prestamo', 'Préstamo'), ('adelanto', 'Adelanto'), ('fiscal', 'Retención fiscal'), ('seguridad_social', 'Seguridad social'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('fecha_aplicacion', models.DateField(verbose_name='Fecha de aplicación')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('cuotas_totales', models.IntegerField(blank=True, help_text='Si es un préstamo, cuántas cuotas tiene', null=True, verbose_name='Cuotas totales')),
                ('cuota_actual', models.IntegerField(blank=True, null=True, verbose_name='Cuota actual')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descuentos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Descuento',
                'verbose_name_plural': 'Descuentos',
                'ordering': ['-fecha_aplicacion'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(choices=[('por_dia', 'Por día'), ('salario_fijo', 'Salario fijo mensual'), ('mixto', 'Mixto')], default='por_dia', max_length=20, verbose_name='Tipo de pago')),
                ('valor_dia', models.DecimalField(blank=True, decimal_places=2, help_text='Valor por día trabajado (ej: 122000)', max_digits=12, null=True, verbose_name='Valor por día')),
                ('salario_mensual', models.DecimalField(blank=True, decimal_places=2, help_text='Salario mensual si aplica', max_digits=12, null=True, verbose_name='Salario mensual')),
                ('valor_hora_normal', models.DecimalField(blank=True, decimal_places=2, help_text='Valor por hora normal (si se calcula por hora)', max_digits=12, null=True, verbose_name='Valor hora normal')),
                ('valor_hora_extra', models.DecimalField(blank=True, decimal_places=2, help_text='Valor por hora extra', max_digits=12, null=True, verbose_name='Valor hora extra')),
                ('recargo_nocturno_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('35.00'), help_text='Recargo nocturno según ley Colombia (%)', max_digits=5, verbose_name='Recargo nocturno (%)')),
                ('recargo_festivo_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('75.00'), help_text='Recargo festivo según ley Colombia (%)', max_digits=5, verbose_name='Recargo festivo (%)')),
                ('horas_semana_estandar', models.IntegerField(default=42, help_text='Horas estándar semanales antes de extras', verbose_name='Horas semanales')),
                ('dia_pico_placa', models.IntegerField(blank=True, choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], help_text='Día de pico y placa (rota cada 6 meses)', null=True, verbose_name='Día de pico y placa')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_pago', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Configuración de Pago',
                'verbose_name_plural': 'Configuraciones de Pago',
            },
        ),
        migrations.CreateModel(
            name='ReciboPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_periodo', models.CharField(choices=[('quincenal', 'Quincenal'), ('mensual', 'Mensual'), ('semanal', 'Semanal')], default='quincenal', max_length=20, verbose_name='Tipo de período')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha fin')),
                ('horas_normales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Horas normales')),
                ('horas_extras', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Horas extras')),
                ('horas_nocturnas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Horas nocturnas')),
                ('horas_festivas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Horas festivas')),
                ('dias_trabajados', models.IntegerField(default=0, verbose_name='Días trabajados')),
                ('dias_descanso', models.IntegerField(default=0, verbose_name='Días de descanso')),
                ('bruto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Bruto')),
                ('total_descuentos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total descuentos')),
                ('neto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Neto a pagar')),
                ('detalles', models.JSONField(blank=True, default=dict, help_text='Detalle de cálculos: valores por hora, descuentos aplicados, etc.', verbose_name='Detalles')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('aprobado', 'Aprobado'), ('pagado', 'Pagado'), ('anulado', 'Anulado')], default='borrador', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('pdf_path', models.CharField(blank=True, max_length=500, verbose_name='Ruta del PDF')),
                ('enviado_por_email', models.BooleanField(default=False, verbose_name='Enviado por email')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibos_pago', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Recibo de Pago',
                'verbose_name_plural': 'Recibos de Pago',
                'ordering': ['-fecha_inicio', '-creado'],
                'unique_together': {('usuario', 'tipo_periodo', 'fecha_inicio', 'fecha_fin')},
            },
        ),
        migrations.CreateModel(
            name='CalendarioTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('tipo', models.CharField(choices=[('descanso', 'Descanso'), ('licencia_medica', 'Licencia médica'), ('licencia_remunerada', 'Licencia remunerada'), ('licencia_no_remunerada', 'Licencia NO remunerada'), ('pico_placa', 'Pico y placa'), ('feriado', 'Feriado'), ('otro', 'Otro')], max_length=30, verbose_name='Tipo')),
                ('horas_esperadas', models.DecimalField(decimal_places=2, default=Decimal('8.00'), help_text='Horas que debería trabajar este día (0 si es descanso)', max_digits=4, verbose_name='Horas esperadas')),
                ('remunerado', models.BooleanField(default=True, help_text='Si el día se paga aunque no trabaje', verbose_name='¿Remunerado?')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_especiales', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Día Especial',
                'verbose_name_plural': 'Días Especiales',
                'ordering': ['-fecha'],
                'unique_together': {('usuario', 'fecha', 'tipo')},
            },
        ),
    ]
