# Generated by Django 5.2.2 on 2025-06-06 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('solicitado', 'Solicitado'), ('en proceso', 'OT en Proceso'), ('en revision', 'OT en Revisión'), ('finalizada', 'OT Finalizada')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GestionOt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnico', models.CharField(max_length=100)),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnico_asignado', models.CharField(max_length=100)),
                ('fecha_actividad', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CierreOt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mantenimiento', models.CharField(blank=True, max_length=255, null=True)),
                ('materiales_utilizados', models.TextField(blank=True, null=True)),
                ('correo_tecnico', models.EmailField(blank=True, max_length=254, null=True)),
                ('descripcion_falla', models.TextField(blank=True, null=True)),
                ('fecha_inicio_actividad', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('nombre_tecnico', models.CharField(blank=True, max_length=255, null=True)),
                ('causa_falla', models.TextField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('documento_tecnico', models.FileField(blank=True, null=True, upload_to='')),
                ('tipo_intervencion', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion_ot.estado')),
            ],
        ),
    ]
