# Generated by Django 5.2.2 on 2025-06-06 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Gestion_ot', '0001_initial'),
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestionot',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.solicitud'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='estado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion_ot.estado'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='solicitud',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_trabajo', to='solicitudes.solicitud'),
        ),
        migrations.AddField(
            model_name='cierreot',
            name='orden_trabajo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Gestion_ot.ordentrabajo'),
        ),
    ]
