# Generated by Django 6.0.3 on 2026-03-31 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_ot', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierreot',
            name='firma_digital',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cierreot',
            name='se_soluciono',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ImagenCierreOt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='cierre_ot/imagenes/')),
                ('tipo', models.CharField(choices=[('antes', 'Antes'), ('despues', 'Después')], max_length=10)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('cierre_ot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='Gestion_ot.cierreot')),
            ],
        ),
    ]
