# Generated by Django 6.0.3 on 2026-04-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_ot', '0003_cierreot_firma_digital_cierreot_se_soluciono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierreot',
            name='firma_receptor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cierreot',
            name='firma_tecnico',
            field=models.TextField(blank=True, null=True),
        ),
    ]
