# Generated by Django 6.0.3 on 2026-04-01 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_ot', '0004_cierreot_firma_receptor_cierreot_firma_tecnico'),
    ]

    operations = [
    ]
