# Generated by Django 6.0.3 on 2026-04-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_ot', '0005_auto_20260401_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierreot',
            name='documento_receptor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cierreot',
            name='nombre_receptor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cierreot',
            name='documento_tecnico',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
