# Generated by Django 4.2.7 on 2026-04-04 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Activos', '0001_initial'),
        ('Gestion_ot', '0006_cierreot_documento_receptor_cierreot_nombre_receptor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=1, help_text='Orden de ejecución')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='PlanMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Cada cuántos períodos se repite')),
                ('unidad', models.CharField(choices=[('dias', 'Días'), ('semanas', 'Semanas'), ('meses', 'Meses'), ('anios', 'Años')], default='meses', max_length=10)),
                ('fecha_inicio', models.DateField()),
                ('proxima_fecha', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_mantenimiento', to='Activos.equipo')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='TareaMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateField()),
                ('fecha_ejecutada', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=15)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion_ot.actividadmantenimiento')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='Gestion_ot.planmantenimiento')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_mantenimiento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha_programada'],
            },
        ),
        migrations.AddField(
            model_name='actividadmantenimiento',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='Gestion_ot.planmantenimiento'),
        ),
    ]
