# Generated by Django 4.2.7 on 2026-04-14 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_ot', '0007_actividadmantenimiento_planmantenimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareamantenimiento',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('convertido', 'Convertido a OT')], default='pendiente', max_length=15),
        ),
        migrations.CreateModel(
            name='CierreOtActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realizada', models.BooleanField(default=False)),
                ('comentario', models.CharField(blank=True, max_length=255, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_ot.actividadmantenimiento')),
                ('cierre_ot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_cierre', to='Gestion_ot.cierreot')),
            ],
            options={
                'ordering': ['actividad__orden'],
            },
        ),
    ]
