# Generated by Django 4.2.7 on 2026-08-05 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_ot', '0008_alter_tareamantenimiento_estado_cierreotactividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeDriveArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_file_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('mime_type', models.CharField(default='application/pdf', max_length=120)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('download_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('download_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cierre_ot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informe_drive_archivo', to='Gestion_ot.cierreot')),
            ],
        ),
    ]
