# Generated by Django 4.2.7 on 2026-08-10 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_ot', '0009_informedrivearchivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesoInforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.CharField(db_index=True, default='<function uuid4 at 0x000001FFDCF74720>', max_length=64, unique=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('GUARDANDO', 'Guardando'), ('VALIDANDO_ARCHIVOS', 'Validando archivos'), ('GENERANDO_PDF', 'Generando PDF'), ('PDF_LISTO', 'PDF listo'), ('ENVIANDO', 'Enviando'), ('ENVIADO', 'Enviado'), ('ERROR', 'Error')], db_index=True, default='PENDIENTE', max_length=32)),
                ('mensaje', models.CharField(blank=True, default='Pendiente', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('expected_images', models.PositiveIntegerField(default=0)),
                ('confirmed_images', models.PositiveIntegerField(default=0)),
                ('required_signatures', models.JSONField(blank=True, default=list)),
                ('pdf_path', models.CharField(blank=True, max_length=500, null=True)),
                ('pdf_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('email_enviado', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('cierre_ot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos_informe', to='Gestion_ot.cierreot')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='procesoinforme',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['PENDIENTE', 'GUARDANDO', 'VALIDANDO_ARCHIVOS', 'GENERANDO_PDF', 'PDF_LISTO', 'ENVIANDO'])), fields=('cierre_ot',), name='uniq_active_proceso_informe_por_cierre'),
        ),
    ]
