# Generated by Django 4.2.7 on 2026-09-25 18:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_ot', '0010_procesoinforme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesoinforme',
            name='operation_id',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True),
        ),
    ]
