# Generated by Django 4.2.7 on 2026-09-30 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_alter_solicitud_equipo'),
        ('Gestion_ot', '0011_alter_procesoinforme_operation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='solicitud',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orden_trabajo', to='solicitudes.solicitud'),
        ),
    ]
