# Generated by Django 4.2.7 on 2026-09-30 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_ot', '0012_ot_solicitud_unique'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GestionOt',
        ),
    ]
