# Generated by Django 4.2.7 on 2026-09-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_ot', '0013_borrar_gestionot'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesoinforme',
            name='intentos',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad de intentos de procesamiento'),
        ),
    ]
