# Generated by Django 5.2.2 on 2025-06-06 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Activos', '0001_initial'),
        ('Gestion_ot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('consecutivo', models.AutoField(primary_key=True, serialize=False)),
                ('creado_por', models.CharField(max_length=100)),
                ('descripcion_problema', models.TextField()),
                ('email_solicitante', models.EmailField(max_length=254, null=True)),
                ('enviar_email', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('PDV', models.CharField(blank=True, max_length=100, null=True)),
                ('co', models.CharField(blank=True, max_length=100, null=True)),
                ('solicitado_por', models.CharField(default='', max_length=100)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=5)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Activos.equipo')),
                ('estado', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion_ot.estado')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Activos.ubicacion')),
            ],
        ),
    ]
